<a href="https://colab.research.google.com/github/RiteshW991/Machine-Learning/blob/main/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
const= tf.constant([1, 2, 3], dtype=tf.float32)
var = tf.Variable([4, 5, 6], dtype=tf.float32)
mat = tf.constant([[1,2,1],[2,1,4]])

print("Constant Tensor:",const)
print("Variable Tensor:",var)
print("Matrix Tensor:",mat)

Constant Tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Variable Tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>
Matrix Tensor: tf.Tensor(
[[1 2 1]
 [2 1 4]], shape=(2, 3), dtype=int32)


In [ ]:
a = tf.constant(3)
b = tf.constant(4)

sum_ab = tf.add(a, b)
product_ab = tf.multiply(a, b)
print("Sum:", sum_ab.numpy())
print("Product:", product_ab.numpy())

Sum: 7
Product: 12


In [ ]:
my_graph = tf.Graph()
with my_graph.as_default():
    a = tf.constant(2)
    b = tf.constant(3)
    addition = a + b

with tf.compat.v1.Session(graph=my_graph) as sess:
    result = sess.run(addition)
    print("Result of a + b:", result)

Result of a + b: 5


In [ ]:
t = tf.Variable(0)
def increment():
    t.assign(t + 1)

for _ in range(5):
    increment()
    var_value = t.numpy()
    print("After increment:", var_value)

After increment: 1
After increment: 2
After increment: 3
After increment: 4
After increment: 5


In [ ]:
tf.compat.v1.disable_eager_execution()
input = tf.compat.v1.placeholder(tf.float32, shape=(None, 2))
mul = input * 2

with tf.compat.v1.Session() as sess:
    data = [[1, 2], [3, 4], [5, 6]]
    result = sess.run(mul, feed_dict={input: data})
    print("Result:\n", result)

Result:
 [[ 2.  4.]
 [ 6.  8.]
 [10. 12.]]
